import { type ReactNode } from 'react';
import { AlertTriangle, Info, CheckCircle2, XCircle, Sparkles } from 'lucide-react';

interface BadgeProps {
  children: ReactNode;
  variant?: 'teal' | 'navy' | 'red' | 'amber' | 'green';
}

export function Badge({ children, variant = 'teal' }: BadgeProps) {
  const colors: Record<string, string> = {
    teal: 'bg-teal-100 text-teal-700 dark:bg-teal-900/40 dark:text-teal-300',
    navy: 'bg-navy-100 text-navy-700 dark:bg-navy-800 dark:text-navy-200',
    red: 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300',
    amber: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
    green: 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300',
  };
  return (
    <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-medium ${colors[variant]}`}>
      {children}
    </span>
  );
}

export function AIDisclaimer({ variant = 'full' }: { variant?: 'full' | 'compact' }) {
  if (variant === 'compact') {
    return (
      <div className="flex items-center gap-1.5 text-xs text-amber-600 dark:text-amber-400">
        <AlertTriangle className="w-3.5 h-3.5 shrink-0" />
        <span>AI-generated — verify before use</span>
      </div>
    );
  }
  return (
    <div className="flex items-start gap-2.5 rounded-lg bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800/50 px-4 py-3">
      <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
      <div className="text-xs text-amber-800 dark:text-amber-200 space-y-1">
        <p className="font-semibold">AI-Generated Content — Please Review</p>
        <p>
          This content was generated by AI and may contain errors. Always verify dates, calculations,
          legal statements, and tender requirements before use. Do not submit without human review.
        </p>
      </div>
    </div>
  );
}

export function AILabel() {
  return (
    <span className="inline-flex items-center gap-1 text-xs font-medium text-teal-600 dark:text-teal-400">
      <Sparkles className="w-3.5 h-3.5" />
      AI-Generated
    </span>
  );
}

export function EmptyState({ icon, title, description }: { icon: ReactNode; title: string; description: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center animate-fade-in">
      <div className="w-16 h-16 rounded-2xl bg-navy-100 dark:bg-navy-800 flex items-center justify-center text-navy-400 dark:text-navy-500 mb-4">
        {icon}
      </div>
      <h3 className="text-lg font-semibold text-navy-800 dark:text-navy-100 mb-1">{title}</h3>
      <p className="text-sm text-navy-400 dark:text-navy-500 max-w-sm">{description}</p>
    </div>
  );
}

export function LoadingDots() {
  return (
    <div className="flex items-center gap-1.5 py-2">
      <span className="typing-dot" />
      <span className="typing-dot" />
      <span className="typing-dot" />
    </div>
  );
}

export function Spinner({ className = '' }: { className?: string }) {
  return (
    <svg className={`animate-spin ${className}`} viewBox="0 0 24 24" fill="none">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
    </svg>
  );
}

export function Alert({ type, children }: { type: 'info' | 'warning' | 'error' | 'success'; children: ReactNode }) {
  const config = {
    info: { icon: Info, cls: 'bg-[#F5F0E8] dark:bg-navy-800 text-navy-700 dark:text-[#E8DFD0] border-[#E8DFD0] dark:border-navy-700' },
    warning: { icon: AlertTriangle, cls: 'bg-amber-50 dark:bg-amber-900/20 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800/50' },
    error: { icon: XCircle, cls: 'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-300 border-red-200 dark:border-red-800/50' },
    success: { icon: CheckCircle2, cls: 'bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-300 border-green-200 dark:border-green-800/50' },
  };
  const Icon = config[type].icon;
  return (
    <div className={`flex items-start gap-2.5 rounded-lg border px-4 py-3 ${config[type].cls}`}>
      <Icon className="w-4 h-4 shrink-0 mt-0.5" />
      <div className="text-sm">{children}</div>
    </div>
  );
}
